/*
Generated by UnityTwine on 02/18/2017 11:28:16
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class BankAdventure: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"You woke up in a small room.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You stare at the dirty ceiling for several minutes but can't remenber anything of yourself.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You are wearing a T-shirt and a pair of pants. Nothing special but there seems something in the right pocket of the trousers.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It is a piece of paper, a piece of paper with '");
		yield return new TwineLink(@"go to the bank", @"go to the bank", @"go to the bank", null, null);
		yield return new TwineText(@"' written on it.");	
	}
    
	// .............
	// #1: StoryTitle

	void passageInit_1()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"BankAdventure");	
	}
    
	// .............
	// #2: StoryAuthor

	void passageInit_2()
	{
		this.Passages["StoryAuthor"] = new TwinePassage("StoryAuthor", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"Anonymous");	
	}
    
	// .............
	// #3: go to the bank

	void passageInit_3()
	{
		this.Passages["go to the bank"] = new TwinePassage("go to the bank", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"You open the door and go downstairs, and you see a man at the front desk - he may know something about you.");
		yield return new TwineText(@"​");
		yield return new TwineLink(@"Talk to him", @"Talk to him", @"Talk to him", null, null);
		yield return new TwineLink(@"Leave directly", @"Leave directly", @"Leave directly", null, null);	
	}
    
	// .............
	// #4: Talk to him

	void passageInit_4()
	{
		this.Passages["Talk to him"] = new TwinePassage("Talk to him", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"""Are you the employee of this...eee..hotel?""");
		yield return new TwineText(@"""Yes, my name is Robert."" ");
		yield return new TwineText(@"""Do you know something about me? I don't know why I lose my memory.""");
		yield return new TwineText(@"""Your name is Adam, that's the only thing I know about you.""");
		yield return new TwineText(@"");
		yield return new TwineText(@"When you try to ask more, he answers with almost same words everytime.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Leave", @"Leave", @"Leave directly", null, null);	
	}
    
	// .............
	// #5: Leave directly

	void passageInit_5()
	{
		this.Passages["Leave directly"] = new TwinePassage("Leave directly", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"You come to the outside.");
		yield return new TwineText(@"There is no one else on the street.");
		yield return new TwineText(@"");
		yield return new TwineText(@"How do you find the bank?");
		yield return new TwineLink(@"Depends on intuition", @"Depends on intuition", @"Depends on intuition", null, null);
		yield return new TwineLink(@"Try to find a map", @"Try to find a map", @"Try to find a map", null, null);	
	}
    
	// .............
	// #6: Try to find a map

	void passageInit_6()
	{
		this.Passages["Try to find a map"] = new TwinePassage("Try to find a map", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"At somewhere on the street, you successfully found a map.");
		yield return new TwineText(@"It shows how to go to the bank");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Get to the bank", @"Get to the bank", @"get to the bank", null, null);
		//yield return new TwineText(@".");	
	}
    
	// .............
	// #7: Depends on intuition

	void passageInit_7()
	{
		this.Passages["Depends on intuition"] = new TwinePassage("Depends on intuition", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"You are wandering through the street.");
		yield return new TwineText(@"You see an old women walking on the street. ");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Talk to her", @"Talk to her", @"Talk to her", null, null);	
		yield return new TwineLink(@"Ignore",@"Ignore",@"get to the bank",null,null);
	}
    
	// .............
	// #8: get to the bank

	void passageInit_8()
	{
		this.Passages["get to the bank"] = new TwinePassage("get to the bank", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"You walked into the bank.");
		yield return new TwineText(@"There is a man who is standing at the front desk.");
		yield return new TwineText(@"");
		yield return new TwineText(@"He looks as same as the man in the hotel.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""Hi Adam, I am waiting for you. Here is your memory stored."" The man say after he looks me up and down,""Do you want to read your memory?""");
		yield return new TwineText(@"");
		yield return new TwineLink(@"""Yes.""", @"""Yes.""", @"End", null, null);	
	}
    
	// .............
	// #9: Talk to her

	void passageInit_9()
	{
		this.Passages["Talk to her"] = new TwinePassage("Talk to her", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"You find she is in an even worse situation than you as she know  neither her name nor her destination.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Bring her to the bank together", @"Bring her to the bank together", @"Bring her to the bank together", null, null);	
		yield return new TwineLink(@"Leave", @"Leave", @"get to the bank", null, null);	
	}
    
	// .............
	// #10: Bring her to the bank together

	void passageInit_10()
	{
		this.Passages["Bring her to the bank together"] = new TwinePassage("Bring her to the bank together", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"You suggest she can come with you and she is also glad to have a companion. Surprisingly, the old women and you feel like old friends when you start chating. You want to spend more time with her.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It seems that time passes faster when you enjoy talking with each other. Even though you spend little attention finding the bank, suddenly it turns up in front of you two.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Enter the bank with the old women", @"Enter the bank with the old women", @"Enter the bank with the old women", null, null);	
	}
    
	// .............
	// #11: Enter the bank with the old women

	void passageInit_11()
	{
		this.Passages["Enter the bank with the old women"] = new TwinePassage("Enter the bank with the old women", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"There is a man who is standing at the front desk.");
		yield return new TwineText(@"");
		yield return new TwineText(@"He looks as same as the man in the hotel.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""Hi Adam, I am waiting for you. Here is your memory stored here."" The man say after he look me up and down. Then he does the same thing to the old women and say,""Hi Eve, I am waiting for you. Here is your memory stored here."" ");
		yield return new TwineText(@"Eve is happy to know her name, and she ask,""How long will it take for us to read our memory?""");
		yield return new TwineText(@"The man answer, ""I'm afraid it will take the rest of the day to go through both of them.""");
		yield return new TwineText(@"");
		yield return new TwineText(@"Now you decide to");
		yield return new TwineLink(@"Read memory", @"Read memory", @"Read memory", null, null);
		yield return new TwineLink(@"Ask Eve if she want to spend the rest of the day with you", @"Ask Eve if she want to spend the rest of the day with you", @"Ask Eve if she want to spend the rest of the day with you", null, null);	
	}
    
	// .............
	// #12: Read memory

	void passageInit_12()
	{
		this.Passages["Read memory"] = new TwinePassage("Read memory", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"You spent the rest of the day going through your memory. ");
		yield return new TwineText(@"You know who you are and Eve is the one you have been searching for dozens of years. And you know two of you will forget everything tomorrow again.");
		yield return new TwineText(@"You turn your head to find Eve and find that she is watching you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""Happy to see you again."", You say.");
		yield return new TwineText(@"""Me too.""");
		yield return new TwineText(@"""There is no more things I care on the world."", You say.");
		yield return new TwineText(@"""Me too.""");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Human beings die out on this day.");	
	}
    
	// .............
	// #13: Ask Eve if she want to spend the rest of the day with you

	void passageInit_13()
	{
		this.Passages["Ask Eve if she want to spend the rest of the day with you"] = new TwinePassage("Ask Eve if she want to spend the rest of the day with you", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"Eve agree.");
		yield return new TwineText(@"Two of you had a really nice day.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""You know, I think we may be couple before."" You said.");
		yield return new TwineText(@"""So do I."" She said.");
		yield return new TwineText(@"");
		yield return new TwineText(@"After the day, you farewelled to Eve, returned to the hotel and plan to go to the bank tomorrow.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You fell asleep with the happy memory that you created with Eve today.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Next Day", @"Next Day", @"Start", null, null);	
	}
    
	// .............
	// #14: End

	void passageInit_14()
	{
		this.Passages["End"] = new TwinePassage("End", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"You spent the rest of the day going through your memory. ");
		yield return new TwineText(@"After that, you know who you are. You have a lover but you do not know where she is now. And soon, you will lose all your memory again.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""I should not forget her. I must find her."" You think.");
		yield return new TwineText(@"So you went back to the hotel.");
		yield return new TwineText(@"Before going to sleep, you put the note for yourself in the right pocket of your trousers.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Next day", @"Next day", @"Start", null, null);	
	}

}